#Need to clean up
#Currently uses ts_to and ts_from in epoch date format to delete pdf files
#See 
#files.list https://api.slack.com/methods/files.list
#files.delete https://api.slack.com/methods/files.delete
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
  - name: get files from slack
    uri:
      url: https://slack.com/api/files.list?ts_to=1514808000&ts_from=1483272000&types=pdfs
      method: GET
      force_basic_auth: yes
      headers:
        Content-type: "application/x-www-form-urlencoded"
        Authorization: Bearer xoxp-xoxp-batman-robin-superman-tsoukalos-yourtoken
      return_content: yes
    register: filelist

#Not really needed, just here to test so I can see what files are being deleted
  - name: write list of files - just for testing/validation
    copy:
      content: "{{ filelist | to_nice_json }}"
      dest: "files.txt"

  - name: delete files
    uri:
      url: "https://slack.com/api/files.delete?file={{ item.id }}"
      method: POST
      force_basic_auth: yes
      headers:
        Content-type: "application/x-www-form-urlencoded"
        Authorization: Bearer xoxp-xoxp-batman-robin-superman-tsoukalos-yourtoken
    with_items: "{{ filelist.json.files }}"
